FROM node:20-slim

WORKDIR /app

# 開発に必要なパッケージをインストール
RUN npm install -g npm@latest

# package.jsonが存在する場合はコピーして依存関係をインストール
COPY package*.json* ./
RUN if [ -f "package.json" ]; then npm install; else echo "No package.json found. Will initialize later."; fi

# ソースコードをコピー
COPY . .

# 追加の依存関係をインストール
RUN npm install --save-dev react-app-rewired webpack-bundle-tracker

# ポートの設定
EXPOSE 3000

# 開発サーバーを起動
CMD ["npm", "start"]